//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int ID { get; set; }
        public string ekle { get; set; }
        public string image { get; set; }
        public Nullable<int> fiyat { get; set; }
    }
}
