//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        public int Carid { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> Carikod { get; set; }
        public string Cariad { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Vergikimlik { get; set; }
        public Nullable<int> Silindimi { get; set; }
    }
}
