//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
        public string Ad_soyad { get; set; }
        public string kullanıcı_adi { get; set; }
        public string Sifre { get; set; }
        public string Rol { get; set; }
        public Nullable<int> Silindimi { get; set; }
    }
}
