//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Nullable<System.DateTime> Mdate { get; set; }
        public string Musteri_adi { get; set; }
        public string Musteri_sifresi { get; set; }
        public string Musteri_eposta { get; set; }
        public int Musteri_id { get; set; }
        public string yetki { get; set; }
    }
}
