//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int Stokid { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string Stokkodu { get; set; }
        public string Stokadi { get; set; }
        public Nullable<int> Silindimi { get; set; }
        public string Resim { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    }
}
